# Load dependency

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from scipy import stats

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer, IterativeImputerte

# Load data

In [4]:
coffee_data = '../data/arabica_data_cleaned.csv'

cf = pd.read_csv(coffee_data)
cf = cf.iloc[:, 1:] # ship the number column

In [5]:
cf.head()

,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,Region,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,NaN,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,oromia,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [7]:
feature_selected = [
    'Country.of.Origin', 'Variety', 
    'Processing.Method', 'Moisture', 
    'unit_of_measurement', 'Color', 
    'altitude_mean_meters', 'Total.Cup.Points'
]
cf = cf[feature_selected]
cf

,Country.of.Origin,Variety,Processing.Method,Moisture,unit_of_measurement,Color,altitude_mean_meters,Total.Cup.Points
0,Ethiopia,NaN,Washed / Wet,0.12,m,Green,2075.00,90.58
1,Ethiopia,Other,Washed / Wet,0.12,m,Green,2075.00,89.92
2,Guatemala,Bourbon,NaN,0.00,m,NaN,1700.00,89.75
3,Ethiopia,NaN,Natural / Dry,0.11,m,Green,2000.00,89.00
4,Ethiopia,Other,Washed / Wet,0.12,m,Green,2075.00,88.83
...,...,...,...,...,...,...,...,...
1306,Mexico,Bourbon,Washed / Wet,0.11,m,None,900.00,68.33
1307,Haiti,Typica,Natural / Dry,0.14,m,Blue-Green,350.00,67.92
1308,Nicaragua,Caturra,Other,0.13,m,Green,1100.00,63.08
1309,Guatemala,Catuai,Washed / Wet,0.10,ft,Green,1417.32,59.83
1310,Honduras,Caturra,NaN,0.12,m,Green,1400.00,0.00

In [8]:
cf.columns = cf.columns.str.replace('.', '_')
cf.columns = cf.columns.str.title()
cf

/var/folders/cd/mt3mnkz168n9wr_y2d10dqb80000gn/T/ipykernel_99244/2722055113.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  cf.columns = cf.columns.str.replace('.', '_')

,Country_Of_Origin,Variety,Processing_Method,Moisture,Unit_Of_Measurement,Color,Altitude_Mean_Meters,Total_Cup_Points
0,Ethiopia,NaN,Washed / Wet,0.12,m,Green,2075.00,90.58
1,Ethiopia,Other,Washed / Wet,0.12,m,Green,2075.00,89.92
2,Guatemala,Bourbon,NaN,0.00,m,NaN,1700.00,89.75
3,Ethiopia,NaN,Natural / Dry,0.11,m,Green,2000.00,89.00
4,Ethiopia,Other,Washed / Wet,0.12,m,Green,2075.00,88.83
...,...,...,...,...,...,...,...,...
1306,Mexico,Bourbon,Washed / Wet,0.11,m,None,900.00,68.33
1307,Haiti,Typica,Natural / Dry,0.14,m,Blue-Green,350.00,67.92
1308,Nicaragua,Caturra,Other,0.13,m,Green,1100.00,63.08
1309,Guatemala,Catuai,Washed / Wet,0.10,ft,Green,1417.32,59.83
1310,Honduras,Caturra,NaN,0.12,m,Green,1400.00,0.00

In [9]:
## data cleaning for units
unit_to_convert = cf['Unit_Of_Measurement'].eq('ft')
cf.loc[unit_to_convert, ['Altitude_Mean_Meters']] /= 3.281
cf['Unit_Of_Measurement'].replace(to_replace='ft', value='m', inplace=True)
# cf.drop(columns='unit_of_measurement')

In [10]:
cf.drop(columns="Unit_Of_Measurement", inplace=True)
cf

,Country_Of_Origin,Variety,Processing_Method,Moisture,Color,Altitude_Mean_Meters,Total_Cup_Points
0,Ethiopia,NaN,Washed / Wet,0.12,Green,2075.000000,90.58
1,Ethiopia,Other,Washed / Wet,0.12,Green,2075.000000,89.92
2,Guatemala,Bourbon,NaN,0.00,NaN,1700.000000,89.75
3,Ethiopia,NaN,Natural / Dry,0.11,Green,2000.000000,89.00
4,Ethiopia,Other,Washed / Wet,0.12,Green,2075.000000,88.83
...,...,...,...,...,...,...,...
1306,Mexico,Bourbon,Washed / Wet,0.11,None,900.000000,68.33
1307,Haiti,Typica,Natural / Dry,0.14,Blue-Green,350.000000,67.92
1308,Nicaragua,Caturra,Other,0.13,Green,1100.000000,63.08
1309,Guatemala,Catuai,Washed / Wet,0.10,Green,431.978055,59.83
1310,Honduras,Caturra,NaN,0.12,Green,1400.000000,0.00

# split and preprocessing

In [11]:
X = cf.iloc[:, cf.columns != "Total_Cup_Points"]
y = cf["Total_Cup_Points"]
seed = 42

X_other, X_test, y_other, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=seed)
X_train, X_val, y_train, y_val = train_test_split(X_other, y_other, test_size=0.25, shuffle=True, random_state=seed)

In [12]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(786, 6)
(262, 6)
(263, 6)

In [15]:
oh_ftr_list = ['Country_Of_Origin', 'Variety',
               'Processing_Method', 'Color']
std_ftr_list = ["Moisture", "Altitude_Mean_Meters"]

categorical_transformer = Pipeline(
    steps=
    [
        ("imputer", SimpleImputer(strategy="constant", fill_value="missing")),
        ('onehot', OneHotEncoder(sparse=False, handle_unknown='ignore'))
    ]
)

numerical_transformer = Pipeline(
    steps=[
    ("scaler", StandardScaler())
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, oh_ftr_list), 
        ('num', numerical_transformer, std_ftr_list)
    ]
)

X_train_prep = preprocessor.fit_transform(X_train)
X_test_prep = preprocessor.transform(X_test)
X_val_prep = preprocessor.transform(X_val)
feature_names = preprocessor.get_feature_names_out()
feature_names

array(['cat__Country_Of_Origin_Brazil', 'cat__Country_Of_Origin_Burundi',
       'cat__Country_Of_Origin_China', 'cat__Country_Of_Origin_Colombia',
       'cat__Country_Of_Origin_Costa Rica',
       'cat__Country_Of_Origin_El Salvador',
       'cat__Country_Of_Origin_Ethiopia',
       'cat__Country_Of_Origin_Guatemala', 'cat__Country_Of_Origin_Haiti',
       'cat__Country_Of_Origin_Honduras',
       'cat__Country_Of_Origin_Indonesia', 'cat__Country_Of_Origin_Japan',
       'cat__Country_Of_Origin_Kenya', 'cat__Country_Of_Origin_Laos',
       'cat__Country_Of_Origin_Malawi',
       'cat__Country_Of_Origin_Mauritius',
       'cat__Country_Of_Origin_Mexico', 'cat__Country_Of_Origin_Myanmar',
       'cat__Country_Of_Origin_Nicaragua',
       'cat__Country_Of_Origin_Panama', 'cat__Country_Of_Origin_Peru',
       'cat__Country_Of_Origin_Philippines',
       'cat__Country_Of_Origin_Rwanda', 'cat__Country_Of_Origin_Taiwan',
       'cat__Country_Of_Origin_Tanzania, United Republic Of',
       'cat__Country_Of_Origin_Thailand', 'cat__Country_Of_Origin_Uganda',
       'cat__Country_Of_Origin_United States',
       'cat__Country_Of_Origin_United States (Hawaii)',
       'cat__Country_Of_Origin_United States (Puerto Rico)',
       'cat__Country_Of_Origin_Vietnam', 'cat__Country_Of_Origin_Zambia',
       'cat__Variety_Arusha', 'cat__Variety_Bourbon',
       'cat__Variety_Catimor', 'cat__Variety_Catuai',
       'cat__Variety_Caturra', 'cat__Variety_Ethiopian Heirlooms',
       'cat__Variety_Ethiopian Yirgacheffe', 'cat__Variety_Gesha',
       'cat__Variety_Hawaiian Kona', 'cat__Variety_Java',
       'cat__Variety_Mandheling', 'cat__Variety_Marigojipe',
       'cat__Variety_Mundo Novo', 'cat__Variety_Other',
       'cat__Variety_Pacamara', 'cat__Variety_Pacas',
       'cat__Variety_Pache Comun', 'cat__Variety_Peaberry',
       'cat__Variety_Ruiru 11', 'cat__Variety_SL14', 'cat__Variety_SL28',
       'cat__Variety_SL34', 'cat__Variety_Typica',
       'cat__Variety_Yellow Bourbon', 'cat__Variety_missing',
       'cat__Processing_Method_Natural / Dry',
       'cat__Processing_Method_Other',
       'cat__Processing_Method_Pulped natural / honey',
       'cat__Processing_Method_Semi-washed / Semi-pulped',
       'cat__Processing_Method_Washed / Wet',
       'cat__Processing_Method_missing', 'cat__Color_Blue-Green',
       'cat__Color_Bluish-Green', 'cat__Color_Green', 'cat__Color_None',
       'cat__Color_missing', 'num__Moisture', 'num__Altitude_Mean_Meters'],
      dtype=object)

# model construction

In [16]:
import tensorflow as tf

In [20]:
learning_rate_schedule = tf.keras.optimizer

297     83.75
3       89.00
966     81.25
579     82.75
288     83.83
        ...
249     84.00
1166    79.58
1148    79.75
1130    79.92
1230    78.33
Name: Total_Cup_Points, Length: 786, dtype: float64

In [61]:
model = tf.keras.Sequential(
    layers=[
        tf.keras.layers.Dense(units=128, activation=tf.keras.layers.LeakyReLU(alpha=0.2)),
        tf.keras.layers.BatchNormalization(),
#         tf.keras.layers.Dense(units=32, activation=tf.keras.layers.LeakyReLU(alpha=0.2)),
#         tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(units=1),
        tf.keras.layers.ActivityRegularization(l1=2.0),
        tf.keras.layers.Rescaling(scale=5, offset=82)
    ]
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(2e-1),
    loss=tf.keras.losses.mean_absolute_error,
    metrics=tf.keras.metrics.mean_absolute_error
)

model.fit(
    x=X_train_prep,
    y=y_train,
    batch_size=5,
    epochs=100,
    validation_data=(X_val_prep, y_val),
)

Epoch 1/100

2022-12-01 00:52:25.744528: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

158/158 [==============================] - ETA: 0s - loss: nan - mean_absolute_error: nan

2022-12-01 00:52:28.018594: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

158/158 [==============================] - 3s 12ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 2/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 3/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 4/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 5/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 6/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 7/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 8/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 9/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 10/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 11/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 12/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 13/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 14/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 15/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 16/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 17/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 18/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 19/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 20/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 21/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 22/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 23/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 24/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 25/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 26/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 27/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 28/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 29/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 30/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 31/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 32/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 33/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 34/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 35/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 36/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 37/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 38/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 39/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 40/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 41/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 42/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 43/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 44/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 45/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 46/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 47/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 48/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 49/100
158/158 [==============================] - 1s 8ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 50/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 51/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 52/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 53/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 54/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 55/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 56/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 57/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 58/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 59/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 60/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 61/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 62/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 63/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 64/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 65/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 66/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 67/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 68/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 69/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 70/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 71/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 72/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 73/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 74/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 75/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 76/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 77/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 78/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 79/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 80/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 81/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 82/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 83/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 84/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 85/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 86/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 87/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 88/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 89/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 90/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 91/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 92/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 93/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 94/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 95/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 96/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 97/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 98/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 99/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan
Epoch 100/100
158/158 [==============================] - 1s 7ms/step - loss: nan - mean_absolute_error: nan - val_loss: nan - val_mean_absolute_error: nan

In [59]:
X_train_prep[8]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        , -0.40198878, -0.01838617])

In [27]:
model.predict(X_test_prep)

9/9 [==============================] - 0s 4ms/step

2022-11-30 22:51:28.951194: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)